{
    "inputs": {
        "dependency": "tensorflow",
        "outfile": "/home/vanessa/Desktop/Code/caliper-analysis/.caliper/pypi-tensorflow-2.2.0rc1-python-cp38.json",
        "dockerfile": "FROM python:3.8\nADD . /tmp/repo\nWORKDIR /tmp/repo\nENV LANG C.UTF-8\nENV SHELL /bin/bash\nRUN apt-get update && apt-get install -y wget ca-certificates gnupg2 git\nRUN /bin/bash -c \"wget https://files.pythonhosted.org/packages/68/6e/18612eac04779186c6fbcdc775e675540b12686c0ded38318c960098a040/tensorflow-2.2.0rc1-cp38-cp38-manylinux2010_x86_64.whl && pip install tensorflow-2.2.0rc1-cp38-cp38-manylinux2010_x86_64.whl\"\n",
        "force": false,
        "exists": true,
        "name": "pypi-tensorflow-2.2.0rc1-python-cp38",
        "tests": "tensorflow_v0.11/5_MultiGPU/multigpu_basics.py\ntensorflow_v0.11/1_Introduction/basic_operations.py\ntensorflow_v0.11/1_Introduction/helloworld.py\ntensorflow_v0.11/4_Utils/tensorboard_advanced.py\ntensorflow_v0.11/4_Utils/tensorboard_basic.py\ntensorflow_v0.11/2_BasicModels/logistic_regression.py\ntensorflow_v0.11/2_BasicModels/linear_regression.py\ntensorflow_v0.11/2_BasicModels/nearest_neighbor.py\ntensorflow_v0.11/3_NeuralNetworks/bidirectional_rnn.py\ntensorflow_v0.11/3_NeuralNetworks/autoencoder.py\ntensorflow_v0.11/3_NeuralNetworks/recurrent_network.py\ntensorflow_v0.11/3_NeuralNetworks/dynamic_rnn.py\ntensorflow_v0.11/3_NeuralNetworks/multilayer_perceptron.py\ntensorflow_v0.11/3_NeuralNetworks/convolutional_network.py\ntensorflow_v1/1_Introduction/basic_eager_api.py\ntensorflow_v1/1_Introduction/basic_operations.py\ntensorflow_v1/1_Introduction/helloworld.py\ntensorflow_v1/4_Utils/tensorboard_advanced.py\ntensorflow_v1/4_Utils/tensorboard_basic.py\ntensorflow_v1/5_DataManagement/build_an_image_dataset.py\ntensorflow_v1/5_DataManagement/tensorflow_dataset_api.py\ntensorflow_v1/2_BasicModels/random_forest.py\ntensorflow_v1/2_BasicModels/gradient_boosted_decision_tree.py\ntensorflow_v1/2_BasicModels/logistic_regression.py\ntensorflow_v1/2_BasicModels/word2vec.py\ntensorflow_v1/2_BasicModels/linear_regression.py\ntensorflow_v1/2_BasicModels/logistic_regression_eager_api.py\ntensorflow_v1/2_BasicModels/nearest_neighbor.py\ntensorflow_v1/2_BasicModels/linear_regression_eager_api.py\ntensorflow_v1/2_BasicModels/kmeans.py\ntensorflow_v1/6_MultiGPU/multigpu_basics.py\ntensorflow_v1/6_MultiGPU/multigpu_cnn.py\ntensorflow_v1/3_NeuralNetworks/variational_autoencoder.py\ntensorflow_v1/3_NeuralNetworks/neural_network_eager_api.py\ntensorflow_v1/3_NeuralNetworks/neural_network.py\ntensorflow_v1/3_NeuralNetworks/bidirectional_rnn.py\ntensorflow_v1/3_NeuralNetworks/convolutional_network_raw.py\ntensorflow_v1/3_NeuralNetworks/autoencoder.py\ntensorflow_v1/3_NeuralNetworks/gan.py\ntensorflow_v1/3_NeuralNetworks/recurrent_network.py\ntensorflow_v1/3_NeuralNetworks/neural_network_raw.py\ntensorflow_v1/3_NeuralNetworks/multilayer_perceptron.py\ntensorflow_v1/3_NeuralNetworks/convolutional_network.py",
        "cleanup": true,
        "outdir": "/home/vanessa/Desktop/Code/caliper-analysis"
    },
    "tests": {
        "build": {
            "retval": 0
        },
        "tensorflow_v0.11/5_MultiGPU/multigpu_basics.py": {
            "error": [
                "2021-01-06 00:07:55.494976: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
                "2021-01-06 00:07:55.495079: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)\n",
                "2021-01-06 00:07:55.495166: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (124076d59ad1): /proc/driver/nvidia/version does not exist\n",
                "2021-01-06 00:07:55.495569: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-06 00:07:55.533609: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1999965000 Hz\n",
                "2021-01-06 00:07:55.537755: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f6f94000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
                "2021-01-06 00:07:55.537801: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/5_MultiGPU/multigpu_basics.py\", line 61, in <module>\n",
                "    a = tf.placeholder(tf.float32, [1000, 1000])\n",
                "AttributeError: module 'tensorflow' has no attribute 'placeholder'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.24
        },
        "tensorflow_v0.11/1_Introduction/basic_operations.py": {
            "error": [
                "2021-01-06 00:07:58.572838: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
                "2021-01-06 00:07:58.572871: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)\n",
                "2021-01-06 00:07:58.572893: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (0797d96e96e1): /proc/driver/nvidia/version does not exist\n",
                "2021-01-06 00:07:58.573102: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-06 00:07:58.597663: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1999965000 Hz\n",
                "2021-01-06 00:07:58.598150: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f4250000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
                "2021-01-06 00:07:58.598183: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/1_Introduction/basic_operations.py\", line 25, in <module>\n",
                "    with tf.Session() as sess:\n",
                "AttributeError: module 'tensorflow' has no attribute 'Session'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.74
        },
        "tensorflow_v0.11/1_Introduction/helloworld.py": {
            "error": [
                "2021-01-06 00:08:01.390814: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
                "2021-01-06 00:08:01.390847: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)\n",
                "2021-01-06 00:08:01.390871: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ec30e696cf1f): /proc/driver/nvidia/version does not exist\n",
                "2021-01-06 00:08:01.391118: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-06 00:08:01.413625: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1999965000 Hz\n",
                "2021-01-06 00:08:01.414073: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f3c70000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
                "2021-01-06 00:08:01.414099: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/1_Introduction/helloworld.py\", line 28, in <module>\n",
                "    sess = tf.Session()\n",
                "AttributeError: module 'tensorflow' has no attribute 'Session'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.92
        },
        "tensorflow_v0.11/4_Utils/tensorboard_advanced.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/4_Utils/tensorboard_advanced.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.15
        },
        "tensorflow_v0.11/4_Utils/tensorboard_basic.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/4_Utils/tensorboard_basic.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.72
        },
        "tensorflow_v0.11/2_BasicModels/logistic_regression.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/2_BasicModels/logistic_regression.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.06
        },
        "tensorflow_v0.11/2_BasicModels/linear_regression.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/2_BasicModels/linear_regression.py\", line 73, in <module>\n",
                "    X = tf.placeholder(\"float\")\n",
                "AttributeError: module 'tensorflow' has no attribute 'placeholder'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.8
        },
        "tensorflow_v0.11/2_BasicModels/nearest_neighbor.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/2_BasicModels/nearest_neighbor.py\", line 23, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.69
        },
        "tensorflow_v0.11/3_NeuralNetworks/bidirectional_rnn.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/bidirectional_rnn.py\", line 24, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.11
        },
        "tensorflow_v0.11/3_NeuralNetworks/autoencoder.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/autoencoder.py\", line 25, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.69
        },
        "tensorflow_v0.11/3_NeuralNetworks/recurrent_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/recurrent_network.py\", line 22, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.87
        },
        "tensorflow_v0.11/3_NeuralNetworks/dynamic_rnn.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/dynamic_rnn.py\", line 107, in <module>\n",
                "    x = tf.placeholder(\"float\", [None, seq_max_len, 1])\n",
                "AttributeError: module 'tensorflow' has no attribute 'placeholder'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.13
        },
        "tensorflow_v0.11/3_NeuralNetworks/multilayer_perceptron.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/multilayer_perceptron.py\", line 13, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.78
        },
        "tensorflow_v0.11/3_NeuralNetworks/convolutional_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/convolutional_network.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.14
        },
        "tensorflow_v1/1_Introduction/basic_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/1_Introduction/basic_eager_api.py\", line 23, in <module>\n",
                "    import tensorflow.contrib.eager as tfe\n",
                "ModuleNotFoundError: No module named 'tensorflow.contrib'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.72
        },
        "tensorflow_v1/1_Introduction/basic_operations.py": {
            "error": [
                "2021-01-06 00:08:39.103972: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
                "2021-01-06 00:08:39.104006: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)\n",
                "2021-01-06 00:08:39.104025: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (896fbb6c9c28): /proc/driver/nvidia/version does not exist\n",
                "2021-01-06 00:08:39.104265: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-06 00:08:39.133602: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1999965000 Hz\n",
                "2021-01-06 00:08:39.134057: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f0338000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
                "2021-01-06 00:08:39.134086: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/1_Introduction/basic_operations.py\", line 25, in <module>\n",
                "    with tf.Session() as sess:\n",
                "AttributeError: module 'tensorflow' has no attribute 'Session'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.0
        },
        "tensorflow_v1/1_Introduction/helloworld.py": {
            "error": [
                "2021-01-06 00:08:42.200765: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
                "2021-01-06 00:08:42.200807: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)\n",
                "2021-01-06 00:08:42.200831: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (2044e1b8181c): /proc/driver/nvidia/version does not exist\n",
                "2021-01-06 00:08:42.201108: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-06 00:08:42.229657: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1999965000 Hz\n",
                "2021-01-06 00:08:42.230152: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb440000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
                "2021-01-06 00:08:42.230181: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/1_Introduction/helloworld.py\", line 28, in <module>\n",
                "    sess = tf.Session()\n",
                "AttributeError: module 'tensorflow' has no attribute 'Session'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.91
        },
        "tensorflow_v1/4_Utils/tensorboard_advanced.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/4_Utils/tensorboard_advanced.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.7
        },
        "tensorflow_v1/4_Utils/tensorboard_basic.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/4_Utils/tensorboard_basic.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.02
        },
        "tensorflow_v1/5_DataManagement/build_an_image_dataset.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/5_DataManagement/build_an_image_dataset.py\", line 74, in read_images\n",
                "    classes = sorted(os.walk(dataset_path).next()[1])\n",
                "AttributeError: 'generator' object has no attribute 'next'\n",
                "\n",
                "During handling of the above exception, another exception occurred:\n",
                "\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/5_DataManagement/build_an_image_dataset.py\", line 133, in <module>\n",
                "    X, Y = read_images(DATASET_PATH, MODE, batch_size)\n",
                "  File \"tensorflow_v1/5_DataManagement/build_an_image_dataset.py\", line 76, in read_images\n",
                "    classes = sorted(os.walk(dataset_path).__next__()[1])\n",
                "StopIteration\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.75
        },
        "tensorflow_v1/5_DataManagement/tensorflow_dataset_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/5_DataManagement/tensorflow_dataset_api.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.76
        },
        "tensorflow_v1/2_BasicModels/random_forest.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/random_forest.py\", line 14, in <module>\n",
                "    from tensorflow.contrib.tensor_forest.python import tensor_forest\n",
                "ModuleNotFoundError: No module named 'tensorflow.contrib'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.14
        },
        "tensorflow_v1/2_BasicModels/gradient_boosted_decision_tree.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/gradient_boosted_decision_tree.py\", line 17, in <module>\n",
                "    from tensorflow.contrib.boosted_trees.estimator_batch.estimator import (\n",
                "ModuleNotFoundError: No module named 'tensorflow.contrib'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.71
        },
        "tensorflow_v1/2_BasicModels/logistic_regression.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/logistic_regression.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.96
        },
        "tensorflow_v1/2_BasicModels/word2vec.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/word2vec.py\", line 58, in <module>\n",
                "    filename, _ = urllib.urlretrieve(url, data_path)\n",
                "AttributeError: module 'urllib' has no attribute 'urlretrieve'\n"
            ],
            "output": [
                "Downloading the dataset... (It may take some time)\n"
            ],
            "retval": 1,
            "seconds": 2.87
        },
        "tensorflow_v1/2_BasicModels/linear_regression.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/linear_regression.py\", line 73, in <module>\n",
                "    X = tf.placeholder(\"float\")\n",
                "AttributeError: module 'tensorflow' has no attribute 'placeholder'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.76
        },
        "tensorflow_v1/2_BasicModels/logistic_regression_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/logistic_regression_eager_api.py\", line 20, in <module>\n",
                "    tf.enable_eager_execution()\n",
                "AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.27
        },
        "tensorflow_v1/2_BasicModels/nearest_neighbor.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/nearest_neighbor.py\", line 23, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.83
        },
        "tensorflow_v1/2_BasicModels/linear_regression_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/linear_regression_eager_api.py\", line 21, in <module>\n",
                "    tf.enable_eager_execution()\n",
                "AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.27
        },
        "tensorflow_v1/2_BasicModels/kmeans.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/kmeans.py\", line 17, in <module>\n",
                "    from tensorflow.contrib.factorization import KMeans\n",
                "ModuleNotFoundError: No module named 'tensorflow.contrib'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.76
        },
        "tensorflow_v1/6_MultiGPU/multigpu_basics.py": {
            "error": [
                "2021-01-06 00:09:23.441902: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
                "2021-01-06 00:09:23.441949: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)\n",
                "2021-01-06 00:09:23.441989: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (b647aef42994): /proc/driver/nvidia/version does not exist\n",
                "2021-01-06 00:09:23.442338: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-06 00:09:23.465614: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1999965000 Hz\n",
                "2021-01-06 00:09:23.466032: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f5658000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
                "2021-01-06 00:09:23.466065: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/6_MultiGPU/multigpu_basics.py\", line 61, in <module>\n",
                "    a = tf.placeholder(tf.float32, [1000, 1000])\n",
                "AttributeError: module 'tensorflow' has no attribute 'placeholder'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.38
        },
        "tensorflow_v1/6_MultiGPU/multigpu_cnn.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/6_MultiGPU/multigpu_cnn.py\", line 28, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.76
        },
        "tensorflow_v1/3_NeuralNetworks/variational_autoencoder.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/variational_autoencoder.py\", line 35, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.11
        },
        "tensorflow_v1/3_NeuralNetworks/neural_network_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/neural_network_eager_api.py\", line 26, in <module>\n",
                "    tf.enable_eager_execution()\n",
                "AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.73
        },
        "tensorflow_v1/3_NeuralNetworks/neural_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/neural_network.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.76
        },
        "tensorflow_v1/3_NeuralNetworks/bidirectional_rnn.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/bidirectional_rnn.py\", line 18, in <module>\n",
                "    from tensorflow.contrib import rnn\n",
                "ModuleNotFoundError: No module named 'tensorflow.contrib'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.04
        },
        "tensorflow_v1/3_NeuralNetworks/convolutional_network_raw.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/convolutional_network_raw.py\", line 16, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.7
        },
        "tensorflow_v1/3_NeuralNetworks/autoencoder.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/autoencoder.py\", line 30, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.85
        },
        "tensorflow_v1/3_NeuralNetworks/gan.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/gan.py\", line 35, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.97
        },
        "tensorflow_v1/3_NeuralNetworks/recurrent_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/recurrent_network.py\", line 17, in <module>\n",
                "    from tensorflow.contrib import rnn\n",
                "ModuleNotFoundError: No module named 'tensorflow.contrib'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.73
        },
        "tensorflow_v1/3_NeuralNetworks/neural_network_raw.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/neural_network_raw.py\", line 17, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.09
        },
        "tensorflow_v1/3_NeuralNetworks/multilayer_perceptron.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/multilayer_perceptron.py\", line 24, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 2.65
        },
        "tensorflow_v1/3_NeuralNetworks/convolutional_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/convolutional_network.py\", line 16, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "ModuleNotFoundError: No module named 'tensorflow.examples.tutorials'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 3.1
        }
    },
    "requirements.txt": [
        "absl-py==0.11.0\n",
        "astunparse==1.6.3\n",
        "cachetools==4.2.0\n",
        "certifi==2020.12.5\n",
        "chardet==4.0.0\n",
        "gast==0.3.3\n",
        "google-auth==1.24.0\n",
        "google-auth-oauthlib==0.4.2\n",
        "google-pasta==0.2.0\n",
        "grpcio==1.34.0\n",
        "h5py==2.10.0\n",
        "idna==2.10\n",
        "Keras-Preprocessing==1.1.2\n",
        "Markdown==3.3.3\n",
        "numpy==1.19.5\n",
        "oauthlib==3.1.0\n",
        "opt-einsum==3.3.0\n",
        "protobuf==3.14.0\n",
        "pyasn1==0.4.8\n",
        "pyasn1-modules==0.2.8\n",
        "requests==2.25.1\n",
        "requests-oauthlib==1.3.0\n",
        "rsa==4.6\n",
        "scipy==1.4.1\n",
        "six==1.15.0\n",
        "tensorboard==2.1.1\n",
        "tensorflow @ file:///tmp/repo/tensorflow-2.2.0rc1-cp38-cp38-manylinux2010_x86_64.whl\n",
        "tensorflow-estimator==2.2.0\n",
        "termcolor==1.1.0\n",
        "urllib3==1.26.2\n",
        "Werkzeug==1.0.1\n",
        "wrapt==1.12.1\n"
    ]
}